name: your_env_name
channels:
- defaults
- conda-forge
- bioconda
dependencies:
- r-base
- r-tidyselect=1.2.0
- r-dplyr=1.1.4
- r-blob=1.2.4
- r-graphics=4.3.0
- r-fastmap=1.1.1
- r-WorldFlora=1.14.2
- r-promises=1.2.1
- r-digest=0.6.34
- r-rpart=4.1.19
- r-mime=0.12
- r-lifecycle=1.0.4
- r-sf=1.0.15
- r-ellipsis=0.3.2
- r-survival=3.5.5
- r-base=4.3.0
- r-terra=1.7.71
- r-RSQLite=2.3.1
- r-magrittr=2.0.3
- r-compiler=4.3.0
- r-rlang=1.1.3
- r-tools=4.3.0
- r-yaml=2.3.8
- r-igraph=1.4.3
- r-utf8=1.2.4
- r-gt=0.9.0
- r-data.table=1.15.0
- r-bit=4.0.5
- r-sp=2.1.3
- r-classInt=0.4.10
- r-reticulate=1.38.0
- r-xml2=1.3.4
- r-methods=4.3.0
- r-KernSmooth=2.23.20
- r-withr=3.0.0
- r-purrr=1.0.2
- r-nnet=7.3.19
- r-rWCVP=1.2.4
- r-grid=4.3.0
- r-fansi=1.0.6
- r-grDevices=4.3.0
- r-xtable=1.8.4
- r-e1071=1.7.14
- r-colorspace=2.1.0
- r-future=1.32.0
- r-ada=2.0.5
- r-ggplot2=3.5.1
- r-globals=0.16.2
- r-scales=1.3.0
- r-iterators=1.0.14
- r-MASS=7.3.58.4
- r-cli=3.6.2
- r-utils=4.3.0
- r-generics=0.1.3
- r-rstudioapi=0.15.0
- r-RecordLinkage=0.4.12.4
- r-future.apply=1.11.0
- r-DBI=1.2.1
- r-cachem=1.0.8
- r-proxy=0.4.27
- r-stringr=1.5.1
- r-datasets=4.3.0
- r-splines=4.3.0
- r-parallel=4.3.0
- r-vctrs=0.6.5
- r-Matrix=1.5.4
- r-jsonlite=1.8.8
- r-bit64=4.0.5
- r-listenv=0.9.0
- r-foreach=1.5.2
- r-evd=2.3.6.1
- r-tidyr=1.3.1
- r-units=0.8.5
- r-glue=1.7.0
- r-parallelly=1.36.0
- r-codetools=0.2.19
- r-dismo=1.3.14
- r-stringi=1.8.3
- r-gtable=0.3.4
- r-later=1.3.2
- r-raster=3.6.26
- r-munsell=0.5.0
- r-tibble=3.2.1
- r-pillar=1.9.0
- r-rappdirs=0.3.3
- r-htmltools=0.5.7
- r-ipred=0.9.14
- r-lava=1.7.2.1
- r-gbm=2.1.9
- r-R6=2.5.1
- r-ff=4.0.9
- r-stats=4.3.0
- r-doParallel=1.0.17
- r-shiny=1.8.0
- r-lattice=0.22.5
- r-png=0.1.8
- r-memoise=2.0.1
- r-httpuv=1.6.14
- r-phonics=1.3.10
- r-class=7.3.21
- r-Rcpp=1.0.12
- r-prodlim=2023.3.31
- r-pkgconfig=2.0.3
